# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  # pod 'KUIActionSheet'
  pod 'KUIActionSheet', :git => 'https://github.com/Kofktu/KUIActionSheet.git', :commit => '55602e2977b5a1a513749f17a141d04090268f92'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
